add support for aws Cognito jwt
cfworker/cfworker pull request #105
Opened 2021-03-06 10:33 UTC by advancedtw

fix to support Cognito tokens. the main differences:

1. issuer url requires a path referencing the pool id 
2. the header doesn't have a type field.

2021-03-06 16:22 UTC, jdanyow requested changes
Thanks for the pr, few small changes and I'll merge and ship

2021-03-06 16:22 UTC, jdanyow commented on packages/jwt/src/parse.ts
> -  if (decoded.header.typ !== 'JWT') {
Let's continue to validate typ when it's provided.

2021-03-06 16:22 UTC, jdanyow commented on packages/jwt/src/parse.ts
> +  if (decoded.payload.iss !== issuerOrigin) {
issuerOrigin should be renamed to issuer to match the new logic

2021-03-06 16:22 UTC, jdanyow commented on packages/jwt/test/parse.spec.ts
> -  it('rejects unexpected type', async () => {
Let's keep and add another for cases when typ is not provided

2021-03-06 20:37 UTC, advancedtw commented
I made the changes you requested. in addition I had to make JwtHeader.typ optional.  let me know what you think

2021-03-07 01:11 UTC, jdanyow approved these changes

2021-03-07 01:12 UTC, merged

2021-03-07 15:52 UTC, jdanyow commented
shipped in [@cfworker/jwt 1.6.9](https://www.npmjs.com/package/@cfworker/jwt/v/1.6.9)