Add getPartitionKeyRanges method and types
cfworker/cfworker pull request #176
Opened 2021-12-06 01:10 UTC by Inrixia

RE #170

This adds the `getPartitionKeyRanges` method & arg/return types for fetching `PartitionKeyRanges`.

I have not added tests.

2021-12-06 04:08 UTC, jdanyow requested changes
Please add an integration test in the set of collections tests: 
https://github.com/cfworker/cfworker/blob/main/packages/cosmos/test/client.integration.spec.ts#L55

Something similar to this one is all we need:
https://github.com/cfworker/cfworker/blob/main/packages/cosmos/test/client.integration.spec.ts#L103-L108

2021-12-06 04:08 UTC, jdanyow commented on packages/cosmos/src/types.ts
> +export type PartitionKeyRanges = {
I think the PartitionKeyRanges object will be of type PersistedResource
https://docs.microsoft.com/en-us/rest/api/cosmos-db/get-partition-key-ranges#body-1
```ts
export interface PartitionKeyRanges extends PersistedResource {
  PartitionKeyRanges: PartitionKeyRange[];
   _count: number;
}
```

2021-12-06 04:08 UTC, jdanyow commented on packages/cosmos/src/types.ts
> +export interface PartitionKeyRange extends PersistedResource {
I don't think this extends PersistedResource

2022-02-12 13:54 UTC, closed without merging

2022-02-14 23:05 UTC, Inrixia commented
Yes sorry have been busy. Will eventually get back to this :)